### ISSUE TITLE
I know understand the challenge of Counterfactual Story.

### ISSUE THREAD

**Issue by SCUTykLin** [jiangjiechen/EDUCAT#2]
问题1：
![image](https://user-images.githubusercontent.com/34080744/160641440-4f6236ee-4075-49bc-a41f-eef673790e21.png)
我改的越少，不就越好吗？original text改的越少不就越好吗？我不明白更自然流畅的文本和微小改动之间有什么需要折中的。
问题2：
![image](https://user-images.githubusercontent.com/34080744/160642489-78bfb7d1-d01f-4f5e-a3ee-085b9f0f77ee.png)
大改（massive edits）可以用预训练解决，小改反而有问题？
老铁能解释解释不？
我个人觉得哈，作者的意思应该是，只要我能找到文本中causal invariance的部分并保持其因果关系不变，那么剩下的随便我改，关系不大。

**Comment by jiangjiechen** [comment]
你好，这个trade-off的意思，本问题的难点之一在于需要尽量小地对原结局进行改动（minimal-edits），使得新结局能够与新故事条件的故事逻辑保持一致（coherence）。只对这些关键的部分进行修改就能产生一个新的、符合新故事条件的结局，这件事情是具有挑战性的。大规模的改动更容易带来流畅的结局，小规模的改动可能产生与新条件不通顺的结局，故为trade-off。
The trade-off denotes that one of the key challenges in this task is to make minimal edits to the original ending so that the new one is consistent with the new condition. One can solely edit these important parts of an old ending to create a new one that conforms to the new condition, which is challenging. Massive edits may lead to fluent endings, and minimal edits may cause inconsistent new endings, which makes a trade-off.

你也可以从以下几篇paper里读到相关的描述:
Please refer to these papers that also clarify this point:
- Counterfactual Story Reasoning and Generation
- Back to the Future: Unsupervised Backprop-based Decoding for Counterfactual and Abductive Commonsense Reasoning
- COLD Decoding: Energy-based Constrained Text Generation with Langevin Dynamics

希望这些解答了你的问题，对论文的理解有后续问题可以给我发邮件。
Hope these make sense to you, please email me if you have more questions about the paper.
